#!/usr/bin/env python3
"""Regenerate every progress view from progress.json, the single source of truth.

Writes:
  chapter-01-collection/01-kinesis-data-streams/TRACKER.md   (whole file)
  README.md                                                  (only the marked <!-- progress:... --> blocks)
  assets/study-map.svg                                       (whole file)

Edit progress.json, never the generated parts. Standard library only.
"""
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DATA = json.loads((ROOT / "progress.json").read_text(encoding="utf-8"))
K = DATA["kinesis"]
FOLDER = next(t["folder"] for t in DATA["chapter1_topics"] if t.get("folder"))

ICON = {"done": "🟩", "in-progress": "🟨", "pending": "⬜"}
LABEL = {"done": "✅ Completed", "in-progress": "🔨 In progress", "pending": "⏳ Pending",
         "planned": "⏳ Planned"}


def stats(roadmap):
    n = len(roadmap)
    done = sum(t["status"] == "done" for t in roadmap)
    prog = sum(t["status"] == "in-progress" for t in roadmap)
    return n, done, prog, round(done / n * 100)


def resolve(topic):
    """The Kinesis topic status is derived from its roadmap; the others are set by hand."""
    if topic.get("status") != "auto":
        return topic["status"]
    n, done, prog, _ = stats(K["roadmap"])
    if done == n:
        return "done"
    return "in-progress" if (done or prog) else "planned"


def bar(roadmap):
    return "".join(ICON[t["status"]] for t in roadmap)


# ---------------------------------------------------------------- TRACKER.md
def tracker_md():
    rm = K["roadmap"]
    n, done, prog, pct = stats(rm)
    written = [c for c in K["concepts"] if c["anchor"]]
    pending_write = [c for c in K["concepts"] if not c["anchor"]]
    L = ["<!-- Generated by scripts/update_progress.py from progress.json. Edit progress.json, not this file. -->",
         "# Kinesis Data Streams: learning tracker", "",
         "> AWS Certified Big Data - Specialty · Chapter 1: Collection · Topic 1 · The roadmap for mastering Kinesis Data Streams, one concept at a time.", "",
         bar(rm), "", "🟩 complete · 🟨 in progress · ⬜ pending", "",
         f"**{done} of {n} roadmap topics complete · {prog} in progress · {pct}%**", "",
         f"{len(K['concepts'])} concepts understood: {len(written)} written up in the [Kinesis Data Streams README](README.md) and {len(pending_write)} waiting for their write-up.", "",
         "## Roadmap progress", ""]
    for i, t in enumerate(rm, 1):
        extra = f" (in progress: {t['open']})" if t["status"] == "in-progress" and t.get("open") else ""
        L.append(f"- [{'x' if t['status'] == 'done' else ' '}] {i}. {t['topic']}{extra}")
    L += ["", "## Topic details", "", "| # | Topic | What you will master | Status |", "| :-: | --- | --- | :-: |"]
    for i, t in enumerate(rm, 1):
        L.append(f"| {i} | **{t['topic']}** | {t['covers']} | {LABEL[t['status']]} |")
    L += ["", "## Concepts understood so far", "",
          "Each concept links to its explanation, animation and questions in the [README](README.md). A concept marked pending is understood but not written up yet.", "",
          "| # | Concept | In one line | Written up in |", "| :-: | --- | --- | --- |"]
    for i, c in enumerate(K["concepts"], 1):
        where = f"[README](README.md{c['anchor']})" if c["anchor"] else "⏳ write-up pending"
        L.append(f"| {i} | **{c['name']}** | {c['line']} | {where} |")
    todo = [(i, t) for i, t in enumerate(rm, 1) if t["status"] != "done"]
    L += ["", "## Still to do", ""]
    for i, t in todo:
        note = f": {t['open']}" if t.get("open") else ""
        L.append(f"- {i}. **{t['topic']}**{note}")
    L += ["", f"**Next best topic:** {K['next']}", "",
          "## Current flow you understand", "", "```text", "User Action", "    |", "    v", "Application / Producer", "    |",
          "    | PutRecord / PutRecords", "    v", "Kinesis Stream", "    |", "    +--> Shard 1", "    +--> Shard 2", "    +--> Shard 3",
          "           ^", "           |", "     Partition Key", "     decides routing", "", "Inside each shard:",
          "Record -> Sequence Number -> Ordering", "", "Consumers:", "Standard Consumer", "or", "Enhanced Fan-Out", "```", "",
          "## Hands-on build target (topic 20)", "", "First a simple Python producer and consumer:", "", "```text",
          "Python Producer", "      |", "      | PUT", "      v", "Kinesis Data Stream", "      ^", "      | GET", "      |",
          "Python Consumer", "```", "", "Then extended with more consumers and a path to S3:", "", "```text", "Producer", "   |",
          "   v", "Kinesis", "   |", "   +--> Lambda", "   |", "   +--> Analytics Consumer", "   |", "   +--> S3 path", "```", "",
          "## How progress is kept up to date", "",
          "- This file is **generated**. Do not edit it by hand.",
          "- To change progress, edit [`progress.json`](../../progress.json) (set a topic's `status` to `done`, `in-progress` or `pending`) and commit.",
          "- A GitHub Action then regenerates this tracker, the progress sections of the root README and the study map.",
          "- A topic is `done` when every point in its row is understood. Written explanations, animations and questions live in the [Kinesis Data Streams README](README.md).", ""]
    return "\n".join(L)


# ---------------------------------------------------------------- README blocks
def block(text, name, content):
    pat = re.compile(rf"(<!-- progress:{name}:start -->\n).*?(\n<!-- progress:{name}:end -->)", re.S)
    if not pat.search(text):
        raise SystemExit(f"marker progress:{name} not found in README.md")
    return pat.sub(lambda m: m.group(1) + content + m.group(2), text)


def readme_blocks(text):
    rm = K["roadmap"]
    n, done, prog, pct = stats(rm)
    now = next((t for t in DATA["chapter1_topics"] if resolve(t) == "in-progress"), None)
    summary = []
    if now:
        summary.append(f"**Studying now:** [{now['name']}]({now['folder']}/README.md)" if now.get("folder") else f"**Studying now:** {now['name']}")
    summary += ["", bar(rm), "", f"**{done} of {n} topics complete · {prog} in progress · {pct}%**", "",
                f"**Next up:** {K['next']}", "",
                f"[Read the notes]({FOLDER}/README.md) · [Open the tracker]({FOLDER}/TRACKER.md)"]
    text = block(text, "summary", "\n".join(summary))

    linked = [f"[{c['name']}]({FOLDER}/README.md{c['anchor']})" for c in K["concepts"] if c["anchor"]]
    waiting = [c["name"] for c in K["concepts"] if not c["anchor"]]
    concepts = ["**Written up in the notes:** " + " · ".join(linked)]
    if waiting:
        concepts += ["", "**Understood, write-up pending:** " + " · ".join(waiting)]
    text = block(text, "concepts", "\n".join(concepts))

    ch = ["| Chapter | Topic area | Status |", "| :-: | --- | --- |"]
    for i, c in enumerate(DATA["chapters"], 1):
        ch.append(f"| {i} | {c['name']} | {'🔨 In progress' if c['status']=='in-progress' else '✅ Completed' if c['status']=='done' else '⏳ Planned'} |")
    text = block(text, "chapters", "\n".join(ch))

    tp = ["| # | Topic | Status |", "| :-: | --- | --- |"]
    for i, t in enumerate(DATA["chapter1_topics"], 1):
        s = resolve(t)
        name = f"[{t['name']}]({t['folder']}/README.md) ([tracker]({t['folder']}/TRACKER.md))" if t.get("folder") else t["name"]
        extra = f": {done} of {n} topics complete, {prog} in progress" if t.get("status") == "auto" and s != "planned" else ""
        tp.append(f"| {i} | {name} | {LABEL[s]}{extra} |")
    return block(text, "topics", "\n".join(tp))


# ---------------------------------------------------------------- study map SVG
MONO = "ui-monospace,SFMono-Regular,Menlo,Consolas,monospace"
SANS = '"Segoe UI",Helvetica,Arial,sans-serif'
AMBER, GREEN, BLUE = "#e3b341", "#3fb950", "#58a6ff"


def mover(path, t0, t1, cyc=10.0, r=5, color=BLUE):
    k = lambda t: f"{t / cyc:.4f}"
    return (f'<g opacity="0"><animate attributeName="opacity" values="0;0;1;1;0;0" keyTimes="0;{k(t0)};{k(t0+.03)};{k(t1)};{k(t1+.03)};1" dur="{cyc}s" repeatCount="indefinite"/>'
            f'<circle r="{r}" fill="{color}"/><animateMotion dur="{cyc}s" repeatCount="indefinite" calcMode="linear" keyPoints="0;0;1;1" keyTimes="0;{k(t0)};{k(t1)};1" path="{path}"/></g>')


def study_map():
    rm = K["roadmap"]
    n, done, prog, _ = stats(rm)
    W, H = 960, 330
    css = (f".bg{{fill:#0d1117}} .node{{fill:#161b22;stroke:#30363d;stroke-width:1.5}} .big{{fill:#161b22;stroke:{AMBER};stroke-width:2}} "
           f".done{{fill:#0f1f14;stroke:{GREEN};stroke-width:2}} .t{{font:700 19px {SANS};fill:#e6edf3}} .h{{font:700 15px {SANS};fill:#e6edf3}} "
           f".cap{{font:13px {SANS};fill:#e6edf3}} .mid{{font:12px {SANS};fill:#aab4c0}}")
    b = f'<text x="20" y="36" style="font:700 12px {MONO};fill:#8b949e;letter-spacing:2.5px">AWS CERTIFIED BIG DATA - SPECIALTY  ·  STUDY MAP</text>'
    b += f'<text x="940" y="36" text-anchor="end" style="font:11px {MONO};fill:#7d8590">amber = studying now · green = done · grey = planned</text>'
    chapters = DATA["chapters"][:5]
    pk = ""
    for i, c in enumerate(chapters):
        x = 20 + i * 190
        cur, dn = c["status"] == "in-progress", c["status"] == "done"
        cls = "big" if cur else "done" if dn else "node"
        col = AMBER if cur else GREEN if dn else "#7d8590"
        word = "studying now" if cur else "done" if dn else "planned"
        b += f'<rect x="{x}" y="60" width="160" height="84" rx="14" class="{cls}" style="{"" if (cur or dn) else "opacity:.7"}"/>'
        b += f'<text x="{x+16}" y="84" style="font:700 10px {MONO};fill:{col};letter-spacing:2px">CHAPTER {i+1}</text>'
        b += f'<text x="{x+16}" y="112" class="t">{c["name"]}</text>'
        b += f'<text x="{x+16}" y="132" style="font:11px {MONO};fill:{col}">{"● " if cur else ""}{word}</text>'
        if i < 4:
            b += f'<path d="M{x+160},102 H{x+188}" stroke="#3d444d" stroke-width="2" marker-end="url(#aw)" fill="none"/>'
            for off in (0.4, 5.4):
                pk += mover(f"M{x+160},102 H{x+190}", off + i * 0.5, off + 0.8 + i * 0.5)
    b += f'<g filter="url(#glow)">{pk}</g>'
    b += f'<text x="20" y="168" style="font:700 10px {MONO};fill:#8b949e;letter-spacing:2px">CHAPTER 1 TOPICS</text>'
    chips = DATA["chapter1_topics"]
    rows = [chips[:4], chips[4:]]
    short = {"Amazon Kinesis Data Streams": "Kinesis Data Streams", "Kinesis Data Firehose": "Kinesis Firehose", "Amazon SQS": "SQS", "AWS IoT Core": "IoT Core"}
    num = 0
    for r, row in enumerate(rows):
        x, y = 20, 178 + r * 38
        for t in row:
            num += 1
            s = resolve(t)
            label = f"{num} {short.get(t['name'], t['name'])}"
            w = int(len(label) * 6.6 + 26)
            fill, stroke, tc = ("#2a2208", AMBER, AMBER) if s == "in-progress" else ("#0f1f14", GREEN, GREEN) if s == "done" else ("#11161d", "#30363d", "#8b949e")
            b += f'<rect x="{x}" y="{y}" width="{w}" height="28" rx="8" fill="{fill}" stroke="{stroke}" stroke-width="1.5"/>'
            b += f'<text x="{x+13}" y="{y+18}" style="font:11px {MONO};fill:{tc}">{label}</text>'
            x += w + 10
    b += f'<text x="640" y="168" style="font:700 10px {MONO};fill:#8b949e;letter-spacing:2px">KINESIS DATA STREAMS TRACKER</text>'
    seg = {"done": GREEN, "in-progress": AMBER, "pending": "#30363d"}
    for i, t in enumerate(rm):
        b += f'<rect x="{640+i*15}" y="182" width="12" height="16" rx="3" fill="{seg[t["status"]]}"/>'
    b += f'<text x="640" y="224" class="cap">{done} of {n} topics complete · {prog} in progress</text>'
    b += f'<text x="640" y="244" style="font:11px {MONO};fill:#7d8590">next: {K["next"].lower()}</text>'
    sec = DATA["chapters"][5]
    sw = "planned" if sec["status"] == "planned" else "in progress" if sec["status"] == "in-progress" else "done"
    b += '<rect x="20" y="268" width="920" height="42" rx="12" fill="none" stroke="#3d444d" stroke-width="1.5" stroke-dasharray="3 7"><animate attributeName="stroke-dashoffset" values="0;-20" dur="2s" repeatCount="indefinite"/></rect>'
    b += f'<text x="40" y="294" style="font:700 10px {MONO};fill:#7d8590;letter-spacing:2px">CHAPTER 6</text><text x="130" y="294" class="h">{sec["name"]}</text><text x="215" y="294" class="mid">runs across every stage · {sw}</text>'
    marker = f'<marker id="aw" viewBox="0 0 10 10" refX="8" refY="5" markerWidth="8" markerHeight="8" orient="auto"><path d="M0 0L10 5L0 10z" fill="#8b949e"/></marker>'
    glow = '<filter id="glow" x="-100%" y="-100%" width="300%" height="300%"><feGaussianBlur stdDeviation="3" result="b"/><feMerge><feMergeNode in="b"/><feMergeNode in="SourceGraphic"/></feMerge></filter>'
    return (f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {W} {H}" width="{W}" height="{H}" role="img" aria-labelledby="t d">'
            f'<title id="t">Study map</title><desc id="d">Five chapters from collection to visualization with security across every stage. {done} of {n} Kinesis Data Streams topics are complete.</desc>'
            f'<defs><style>{css}</style>{marker}{glow}</defs><rect class="bg" width="{W}" height="{H}" rx="16"/>{b}</svg>\n')


def write(path, content):
    path = ROOT / path
    old = path.read_text(encoding="utf-8") if path.exists() else None
    if old != content:
        path.write_text(content, encoding="utf-8")
        print(f"updated {path.relative_to(ROOT)}")


if __name__ == "__main__":
    write(f"{FOLDER}/TRACKER.md", tracker_md())
    write("README.md", readme_blocks((ROOT / "README.md").read_text(encoding="utf-8")))
    (ROOT / "assets").mkdir(exist_ok=True)
    write("assets/study-map.svg", study_map())
    print("progress files are up to date")
